"""
Export module.
Outputs generated financial data in three formats:
1. JSON  — Merge.dev list response format
2. CSV   — Flattened tables for Pandas analysis
3. SQL   — PostgreSQL INSERT statements for Supabase
"""

import json
import csv
import os
from dataclasses import asdict
from pathlib import Path


class MergeEncoder(json.JSONEncoder):
    """Handle dataclass serialization and None values."""
    def default(self, obj):
        if hasattr(obj, '__dataclass_fields__'):
            return asdict(obj)
        return super().default(obj)


def ensure_dirs(output_dir: str):
    """Create output directory structure."""
    for sub in ["json", "csv", "sql"]:
        os.makedirs(os.path.join(output_dir, sub), exist_ok=True)


def export_json(items: list, model_name: str, output_dir: str):
    """
    Export a list of model objects as Merge.dev-format JSON.
    Wraps in { "next": null, "previous": null, "results": [...] }
    """
    data = {
        "next": None,
        "previous": None,
        "results": [asdict(item) for item in items],
    }
    path = os.path.join(output_dir, "json", f"{model_name}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, cls=MergeEncoder)
    print(f"  [+] JSON: {path} ({len(items)} records)")


def export_manifest(manifest: list, output_dir: str):
    """Export the anomaly manifest as JSON."""
    path = os.path.join(output_dir, "json", "anomaly_manifest.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    print(f"  [+] Manifest: {path} ({len(manifest)} anomalies)")


def export_monthly_summary(summary: dict, output_dir: str):
    """Export monthly summary as JSON and CSV."""
    # JSON
    path_json = os.path.join(output_dir, "json", "monthly_summary.json")
    with open(path_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    print(f"  [+] Monthly Summary JSON: {path_json}")

    # CSV
    path_csv = os.path.join(output_dir, "csv", "monthly_summary.csv")
    if summary:
        # Flatten months into rows
        rows = []
        for month_num, data in sorted(summary.items(), key=lambda x: int(x[0])):
            row = {"month": month_num}
            row.update(data)
            rows.append(row)

        if rows:
            with open(path_csv, "w", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(f, fieldnames=rows[0].keys())
                writer.writeheader()
                writer.writerows(rows)
            print(f"  [+] Monthly Summary CSV: {path_csv}")


def export_csv(items: list, model_name: str, output_dir: str, fields: list = None):
    """
    Export a list of model objects as a flat CSV.
    Nested objects (lines, addresses) are serialized as JSON strings.
    """
    if not items:
        return

    rows = []
    for item in items:
        d = asdict(item)
        flat = {}
        for k, v in d.items():
            if isinstance(v, (list, dict)):
                flat[k] = json.dumps(v, cls=MergeEncoder)
            else:
                flat[k] = v
        rows.append(flat)

    if fields is None:
        fields = list(rows[0].keys())

    path = os.path.join(output_dir, "csv", f"{model_name}.csv")
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    print(f"  [+] CSV: {path} ({len(rows)} records)")


def _sql_val(v) -> str:
    """Format a Python value for SQL INSERT."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (list, dict)):
        return f"'{json.dumps(v, cls=MergeEncoder).replace(chr(39), chr(39)+chr(39))}'"
    # String — escape single quotes
    s = str(v).replace("'", "''")
    return f"'{s}'"


def export_sql(items: list, table_name: str, output_dir: str, fields: list = None):
    """
    Export a list of model objects as PostgreSQL INSERT statements.
    """
    if not items:
        return

    rows = [asdict(item) for item in items]
    if fields is None:
        fields = list(rows[0].keys())

    path = os.path.join(output_dir, "sql", f"{table_name}.sql")
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"-- {table_name}: {len(rows)} records\n")
        f.write(f"-- Generated by SeedlingLabs Financial Data Generator\n\n")

        for row in rows:
            cols = ", ".join(fields)
            vals = ", ".join(_sql_val(row.get(field)) for field in fields)
            f.write(f"INSERT INTO {table_name} ({cols}) VALUES ({vals});\n")

    print(f"  [+] SQL: {path} ({len(rows)} records)")


def export_company_info(company_info, output_dir: str):
    """Export company metadata."""
    path = os.path.join(output_dir, "json", "company_info.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(asdict(company_info), f, indent=2, cls=MergeEncoder)
    print(f"  [+] Company Info: {path}")


def export_all(
    accounts: list,
    contacts: list,
    expenses: list,
    invoices: list,
    payments: list,
    company_info,
    manifest: list,
    monthly_summary: dict,
    output_dir: str,
):
    """Master export function — writes all formats."""
    ensure_dirs(output_dir)

    print("\n[EXPORT] Exporting financial data...\n")

    # ── JSON (Merge.dev format) ──
    export_json(accounts, "accounts", output_dir)
    export_json(contacts, "contacts", output_dir)
    export_json(expenses, "expenses", output_dir)
    export_json(invoices, "invoices", output_dir)
    export_json(payments, "payments", output_dir)
    export_company_info(company_info, output_dir)
    export_manifest(manifest, output_dir)
    export_monthly_summary(monthly_summary, output_dir)

    # ── CSV ──
    export_csv(accounts, "accounts", output_dir)
    export_csv(contacts, "contacts", output_dir)
    export_csv(expenses, "expenses", output_dir)
    export_csv(invoices, "invoices", output_dir)
    export_csv(payments, "payments", output_dir)

    # ── SQL ──
    export_sql(accounts, "accounts", output_dir)
    export_sql(contacts, "contacts", output_dir)
    export_sql(expenses, "expenses", output_dir)
    export_sql(invoices, "invoices", output_dir)
    export_sql(payments, "payments", output_dir)

    print("\n[OK] Export complete!\n")
